=== Victorjosecordero/Curso21-22/Lenguaje de marca/trabajo_xml/biblioteca_libros.dtd
<!ENTITY % t "(#PCDATA)" >
<!ENTITY img1 SYSTEM "el_asesinato_de_pitagoras.jpg" NDATA jpg >
<!ENTITY img2 SYSTEM "Wordpress_40_La_tela_de_la_araÃ±a.png" NDATA png >
<!NOTATION jpg SYSTEM "image/jpg" >
<!NOTATION png SYSTEM "image/png" >
<!ELEMENT biblioteca (libro)+ >
<!ELEMENT libro (autor+, foto, editorial, edicion, isbn, donacion?, ubicacion) >
    <!ATTLIST libro codigo ID #REQUIRED
                    titulo CDATA #REQUIRED>
<!ELEMENT autor %t; >
<!ELEMENT foto EMPTY >
    <!ATTLIST foto imagen ENTITY #IMPLIED>
<!ELEMENT editorial %t; >
<!ELEMENT edicion %t; >
<!ELEMENT isbn %t; >
<!ELEMENT donacion EMPTY >
<!ELEMENT ubicacion EMPTY >

=== Victorjosecordero/Curso21-22/Lenguaje de marca/trabajo_xml/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca_libros.dtd" [
    <!ATTLIST ubicacion sede (norte | centro | sur) #REQUIRED >
]>
<biblioteca>
    <libro codigo="N10301" titulo="El asesinato de Pitágoras">
        <autor>Marcos Chicot</autor>
        <foto imagen="img1"/>
        <editorial>Duomo Editorial</editorial>
        <edicion>2013</edicion>
        <isbn>9788415945093</isbn>
        <donacion/>
        <ubicacion sede="sur"/>
    </libro>
    <libro codigo="C15234" titulo="Wordpress 4.0 La tela de la araña">
        <autor>Fernando Tellado</autor>
        <autor>Yoani Sánchez</autor>
        <foto imagen="img2"/>
        <editorial>Anaya</editorial>
        <edicion>2016</edicion>
        <isbn>978-84-415-3547-3</isbn>
        <ubicacion sede="centro"/>
    </libro>
</biblioteca>
