<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE declaraciones [
   <!ELEMENT declaraciones (consonante | tipo_de_dato | variable)>
   <!ELEMENT consonante (#PCDATA)>
      <!ATTLIST consonante valor CDATA #REQUIRED>
   <!ELEMENT tipo_de_dato (#PCDATA)>
   <!ELEMENT variable (#PCDATA)>
      <!ATTLIST variable tipo CDATA #REQUIRED>
]>
<declaraciones>
   <consonante valor="3.141592">PI</consonante>
   <variable tipo="real">radio</variable>
   <variable>area</variable>
   <variable>longitud</variable>
</declaraciones>