=== Victorjosecordero/Curso21-22/Lenguaje de marca/trabajo_xml_victor/biblioteca_libros.dtd
<!ENTITY % t "(#PCDATA)" >
<!ENTITY img1 SYSTEM "Lenguajes_de_marca.jpg" NDATA jpg >
<!NOTATION jpg SYSTEM "image/jpg" >
<!ELEMENT biblioteca (libro)+ >
<!ELEMENT libro (autor?, foto, editorial, edicion, isbn, donacion*, ubicacion) >
    <!ATTLIST libro codigo ID #REQUIRED
                    titulo CDATA #REQUIRED>
<!ELEMENT autor %t; >
<!ELEMENT foto EMPTY >
    <!ATTLIST foto imagen ENTITY #IMPLIED>
<!ELEMENT editorial %t; >
<!ELEMENT edicion %t; >
<!ELEMENT isbn %t; >
<!ELEMENT ubicacion EMPTY >

=== Victorjosecordero/Curso21-22/Lenguaje de marca/trabajo_xml_victor/Ejercicio1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca_libros.dtd" [
    <!ATTLIST ubicacion sede (norte | centro | sur) #REQUIRED >
]>
<biblioteca>
    <libro codigo="A66697" titulo="Lenguajes de marcas">
        <autor>Antonio Pino</autor>
        <foto imagen="img1"/>
        <editorial>Santillana</editorial>
        <edicion>2010</edicion>
        <isbn>7895641234567</isbn>
        <donacion/>
        <ubicacion sede="norte"/>
    </libro>
    <libro codigo="T92112" titulo="Python and Java">
        <autor>Cedric Holland</autor>
        <autor>Sara Turner</autor>
        <foto imagen="img2"/>
        <editorial>Oxford</editorial>
        <edicion>2021</edicion>
        <isbn>555-12-983-4752-0</isbn>
        <ubicacion sede="sur"/>
    </libro>
</biblioteca>
